-- MySQL Script generated by MySQL Workbench
-- Mon Dec 19 20:11:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IgnisScript
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IgnisScript
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IgnisScript` DEFAULT CHARACTER SET utf8 ;
USE `IgnisScript` ;

-- -----------------------------------------------------
-- Table `IgnisScript`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IgnisScript`.`Usuario` (
  `matricula` BIGINT NOT NULL,
  `senha` VARCHAR(250) NOT NULL,
  `nome` VARCHAR(300) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IgnisScript`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IgnisScript`.`Setor` (
  `idSetor` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(300) NOT NULL,
  `senha` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idSetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IgnisScript`.`Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IgnisScript`.`Mensagem` (
  `idMensagem` BIGINT NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(5000) NOT NULL,
  `Usuario_matricula` BIGINT NOT NULL,
  `Setor_id` BIGINT NOT NULL,
  PRIMARY KEY (`idMensagem`, `Usuario_matricula`, `Setor_id`),
  INDEX `fk_Mensagem_Usuario_idx` (`Usuario_matricula` ASC),
  INDEX `fk_Mensagem_Setor1_idx` (`Setor_id` ASC),
  CONSTRAINT `fk_Mensagem_Usuario`
    FOREIGN KEY (`Usuario_matricula`)
    REFERENCES `IgnisScript`.`Usuario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensagem_Setor1`
    FOREIGN KEY (`Setor_id`)
    REFERENCES `IgnisScript`.`Setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IgnisScript`.`Tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IgnisScript`.`Tutorial` (
  `idTutorial` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`idTutorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IgnisScript`.`Passo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IgnisScript`.`Passo` (
  `idPasso` BIGINT NOT NULL AUTO_INCREMENT,
  `descriçao` VARCHAR(5000) NOT NULL,
  `imagem` BLOB NULL,
  `Tutorial_idTutorial` BIGINT NOT NULL,
  PRIMARY KEY (`idPasso`, `Tutorial_idTutorial`),
  INDEX `fk_Passo_Tutorial1_idx` (`Tutorial_idTutorial` ASC),
  CONSTRAINT `fk_Passo_Tutorial1`
    FOREIGN KEY (`Tutorial_idTutorial`)
    REFERENCES `IgnisScript`.`Tutorial` (`idTutorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
